-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "SA" SALT '7e441a0081e276e2' HASH '0bbdf6f71b60647869d61998fe8c9cecfd484153e8d9f029d01c353a3d0c6c03' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."USUARIO"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 26) NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "SENHA" CHARACTER VARYING(255) NOT NULL,
    "PONTUACAO" INTEGER
);  
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");      
-- 24 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO;
INSERT INTO "PUBLIC"."USUARIO" VALUES
(1, 'admin', 'admin@gmail.com', 'admin123', 15),
(2, 'usuario20', 'usuario20@usuario20', '123', NULL),
(3, 'usuario11', 'usuario11@email.com', 'senha11', 110),
(4, 'usuario12', 'usuario12@email.com', 'senha12', 120),
(5, 'usuario13', 'usuario13@email.com', 'senha13', 130),
(6, 'usuario14', 'usuario14@email.com', 'senha14', 140),
(7, 'usuario15', 'usuario15@email.com', 'senha15', 150),
(8, 'usuario16', 'usuario16@email.com', 'senha16', 160),
(9, 'usuario17', 'usuario17@email.com', 'senha17', 170),
(10, 'usuario18', 'usuario18@email.com', 'senha18', 180),
(11, 'usuario19', 'usuario19@email.com', 'senha19', 190),
(12, 'usuario20', 'usuario20@usuario20', 'senha20', 200),
(13, 'usuario1', 'usuario1@email.com', 'senha1', NULL),
(14, 'usuario2', 'usuario2@email.com', 'senha2', NULL),
(15, 'usuario3', 'usuario3@email.com', 'senha3', 30),
(16, 'usuario4', 'usuario4@email.com', 'senha4', 40),
(17, 'usuario5', 'usuario5@email.com', 'senha5', 50),
(18, 'usuario6', 'usuario6@email.com', 'senha6', 60),
(19, 'usuario7', 'usuario7@email.com', 'senha7', 70),
(20, 'usuario8', 'usuario8@email.com', 'senha8', 80),
(21, 'usuario9', 'usuario9@email.com', 'senha9', 90),
(22, 'usuario10', 'usuario10@email.com', 'senha10', 100),
(24, 'usuario11', 'usuario11@email.com', 'senha11', -110),
(25, 'bielxrd', 'gabriel.diasramos@hotmail.com', '123', NULL);               
CREATE MEMORY TABLE "PUBLIC"."TEXTOS"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 68) NOT NULL,
    "TEXTO" CHARACTER VARYING(550) NOT NULL,
    "OP1" CHARACTER VARYING(255),
    "REF1" INTEGER,
    "OP2" CHARACTER VARYING(255),
    "REF2" INTEGER,
    "OP3" CHARACTER VARYING(255),
    "REF3" INTEGER,
    "IMAGE" CHARACTER VARYING(255),
    "ESPADA" INTEGER,
    "GRANADA" INTEGER,
    "POCAO" INTEGER,
    "ARMADURA" INTEGER,
    "ESPADADANO" INTEGER,
    "GRANADADANO" INTEGER,
    "POCAOPTS" INTEGER,
    "ARMADURAPTS" INTEGER
);     
ALTER TABLE "PUBLIC"."TEXTOS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");       
-- 64 +/- SELECT COUNT(*) FROM PUBLIC.TEXTOS; 
INSERT INTO "PUBLIC"."TEXTOS" VALUES
(1, U&'Voc\00ea entra em uma sala escura... \00c0 sua frente \00e9 poss\00edvel ouvir um ''SSSSSsssss'' com um breve som de chocalhos. Logo voc\00ea reconhece que se trata de uma cobra', 'Lutar', 2, 'Correr', 4, 'Mochila', 7, 'https://i.imgur.com/EVEJrw4.png', 0, 0, 0, 0, 3, 6, 10, 4),
(2, U&'Voc\00ea tenta lutar contra a cobra com suas m\00e3os nuas, a falta de informa\00e7\00e3o sobre o animal te leva a fazer movimentos imprudentes e voc\00ea \00e9 mordido e envenenado.Aos poucos o veneno come\00e7a a fazer efeito e voc\00ea sente suas for\00e7as se esvaindo, voc\00ea ent\00e3o pode sentir o abra\00e7o da morte.', 'Morte', 3, '0', 0, '0', 0, 'https://staging.cohostcdn.org/attachment/2b9a8afb-a7c8-4d08-881e-c906c7aa3127/pd_05-30-2023_Sneaky.png?width=675&auto=webp&dpr=1', 0, 0, 0, 0, 3, 6, 10, 4),
(3, U&'Voc\00ea morreu! Fim de jogo!', '0', 0, '0', 0, '0', 0, 'https://i.pinimg.com/564x/de/2a/25/de2a259763e36562c87e7333246e25f3.jpg', 0, 0, 0, 0, 3, 6, 10, 4),
(4, U&'Com medo do que o animal seja pe\00e7onhento ou mortal, voc\00ea decide sair da sala, evitando ao m\00e1ximo chamar a aten\00e7\00e3o da cobra.', 'Sucesso', 12, '0', 0, '0', 0, 'https://i.pinimg.com/originals/bf/93/5e/bf935e9ec3a43a2795bfef4b9da1f21c.gif', 0, 0, 0, 0, 3, 6, 10, 4),
(5, U&'Voc\00ea consegue escapar da sala.', '', 0, '', 0, '', 0, 'https://i.pinimg.com/originals/05/8e/fa/058efa2ae3aa1d881d33daca2db63fd6.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(6, U&'Voc\00ea n\00e3o consegue ser silencioso o bastante e chama a aten\00e7\00e3o da cobra. Surpreso e em choque ao ver ela se movendo em sua dire\00e7\00e3o, voc\00ea n\00e3o consegue reagir r\00e1pido o suficiente e \00e9 mordido e envenenado at\00e9 a morte.', 'Morte', 3, '', 0, '', 0, 'https://i.pinimg.com/originals/aa/4f/ac/aa4facb529cea5d120853f39377a41fc.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(7, U&'Abrindo sua mochila e vasculhando por poss\00edveis materiais, voc\00ea encontra uma faca pequena.', 'Equipar', 8, 'Guardar', 8, '', 0, 'https://i.pinimg.com/564x/8c/46/c3/8c46c3f6bf5940f58a2b6d2cea60135a.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(8, U&'Voc\00ea equipou a faca.', 'Equipada', 10, '', 0, '', 0, 'https://i.pinimg.com/564x/8c/46/c3/8c46c3f6bf5940f58a2b6d2cea60135a.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(9, U&'Voc\00ea guardou a faca.', 'Guardada', 11, '', 0, '', 0, 'https://i.pinimg.com/564x/8c/46/c3/8c46c3f6bf5940f58a2b6d2cea60135a.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(10, U&'Ati\00e7ada pelos sons de voc\00ea mexendo em suas coisas, o animal se aproxima ferozmente. J\00e1 esperando por isso, voc\00ea se prepara para o bote. Ela avan\00e7a, e voc\00ea acerta uma estocada certeira em sua cabe\00e7a, finalizando-a. Orgulhoso de seu sucesso, voc\00ea recupera sua faca e abre a pr\00f3xima porta.', 'Sucesso', 12, '', 0, '', 0, 'https://i.pinimg.com/originals/06/f0/61/06f061aecbfca608059b0770f40e5eb1.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(11, U&'Desajeitado enquanto tenta guardar suas coisas novamente, voc\00ea n\00e3o consegue reagir ao ataque e sente uma mordida na sua perna. Assustado, voc\00ea cai no ch\00e3o. A cobra continua te atacando e voc\00ea sente sua vida se esvaindo...', 'Morte', 3, '', 0, '', 0, 'https://i.pinimg.com/originals/b8/83/26/b88326c5a42965963dc961057f66bbf2.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(12, U&'Voc\00ea sai da sala.', 'PORTA1', 21, 'PORTA2', 34, '0', 0, 'https://i.pinimg.com/originals/64/ef/e4/64efe466d05038645d29c25af1af60f5.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(13, U&'O centro da sala est\00e1 bem iluminado, com tamanho destaque no centro, o resto da sala est\00e1 um completo breu. \00c9 poss\00edvel ver um pequeno punhado de moedas de ouro.', 'Pegar', 14, 'Analisar', 15, 'Sair', 16, 'https://i.pinimg.com/originals/36/e6/97/36e6972e7a79897bc34b0795511729b8.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(14, U&'Feliz por encontrar um pouco de sorte finalmente, voc\00ea caminha diretamente at\00e9 elas. Um, dois, tr\00eas, cinco passos, aos poucos voc\00ea vai se aproximando. Quando chega at\00e9 as moedas, voc\00ea se agacha para peg\00e1-las. Ao se abaixar, voc\00ea sente uma coisa fria perfurando seu peito, sangue come\00e7a a subir at\00e9 sua boca rapidamente. Tentando olhar para o local, voc\00ea tem um leve vislumbre de uma faca em suas costas. Uma pequena risada \00e9 ouvida, e voc\00ea cai no ch\00e3o, sentindo a frieza de sua pr\00f3pria pele e uma po\00e7a vermelha crescendo.', 'Morte', 3, '', 0, '', 0, 'https://i.pinimg.com/originals/92/a4/ac/92a4acc3099fdccb91e6c3447c2ed12f.gif', 0, 0, 0, 0, 0, 0, 0, 0);      
INSERT INTO "PUBLIC"."TEXTOS" VALUES
(15, U&'Estranhando a situa\00e7\00e3o, voc\00ea come\00e7a a analisar os arredores ainda melhor. Aos poucos seus olhos se acostumam com a escurid\00e3o e voc\00ea pode ver uma pequena silhueta \00e0 sua direita. Ainda est\00e1 muito escuro, ent\00e3o voc\00ea n\00e3o consegue identificar o que exatamente pode ser.', 'Pegar', 14, 'Sair', 16, '', 0, 'https://i.pinimg.com/564x/c4/20/ef/c420ef3e0fa21e8d13ca124c194cd3b2.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(16, U&'Voc\00ea decide sair da sala, perto da porta \00e9 poss\00edvel ouvir um som de passos r\00e1pidos. Aproveitando que j\00e1 estava perto da porta, voc\00ea sai da sala.', 'Sucesso', 12, '', 0, '', 0, 'https://i.pinimg.com/564x/7b/8b/be/7b8bbe7812c946cb35c6232434d6c6dd.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(17, U&'Ao entrar na sala voc\00ea analisa seus arredores: Um ambiente quadrado com paredes claras, um pouco sujas devido ao tempo, por\00e9m muito bonitas ainda assim. O ch\00e3o se mistura em um quadriculado preto e branco, e ao centro voc\00ea v\00ea uma espada fincada no ch\00e3o.', 'Pegar', 18, 'Analisar', 20, 'Sair', 19, 'https://i.pinimg.com/564x/20/70/43/207043d79482822b9d13d7f185851989.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(18, U&'Voc\00ea se aproxima e repara melhor na arma, \00e9 uma l\00e2mina muito bem forjada, seu fio em perfeito estado e com algumas marca\00e7\00f5es estranhas no cabo. Voc\00ea tenta tirar a espada, fascinado pela beleza dela, e com um pouco de esfor\00e7o voc\00ea consegue remov\00ea-la do ch\00e3o. Voc\00ea adquiriu: Espada leve. Sentindo confian\00e7a com sua l\00e2mina, voc\00ea segue para a pr\00f3xima sala.', 'Sucesso', 12, '', 0, '', 0, 'https://i.pinimg.com/originals/83/8c/14/838c146c50200a44a5c29323fef50d20.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(19, U&'Com receio do que essas escrituras possam ser, voc\00ea decide recuar e n\00e3o tocar na espada. Voc\00ea saiu da sala.', 'Sucesso', 12, '', 0, '', 0, 'https://i.pinimg.com/564x/fb/6c/13/fb6c134b34e9b0d72654747b4f59f7fc.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(20, U&'Com uma estranha sensa\00e7\00e3o de ''algo est\00e1 errado'', voc\00ea decide analisar melhor o quarto, passa pelas paredes cautelosamente, procura no ch\00e3o por algum tipo de armadilha, e ent\00e3o se aproxima da espada o suficiente para analis\00e1-la... Mas nada acontece.', 'Pegar', 18, 'Sair', 19, '', 0, 'https://i.pinimg.com/originals/c4/63/7b/c4637b5fcf27752b7286441994e5776c.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(21, U&'Ao entrar no novo c\00f4modo, voc\00ea logo repara na falta de cor do ambiente, as paredes e ch\00e3o emanam energias negativas. Voc\00ea escuta a porta atr\00e1s de voc\00ea se trancando, logo em seguida voc\00ea consegue escutar um rosnado furioso vindo do centro. Um lobo faminto est\00e1 barrando seu caminho.', 'Atacar', 22, 'Defender', 26, 'Mochila', 29, 'https://i.pinimg.com/originals/42/7d/89/427d89850e4571031d73f9cada4bb58f.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(22, U&'Voc\00ea prepara sua arma e parte para cima do lobo, apesar de n\00e3o ser mais r\00e1pido, sua l\00e2mina consegue cortar uma parte do tronco do animal. Ainda mais raivoso do que antes, ele parte pra cima novamente.', 'Matar', 23, 'Nocautear', 24, '', 0, 'https://i.pinimg.com/originals/33/a4/7e/33a47eb62f7e97e3fcaa565abc2c57bb.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(23, U&'Sabendo de suas capacidades e temendo que ele n\00e3o desista at\00e9 que voc\00ea morra, voc\00ea decide mat\00e1-lo. O lobo ataca ferozmente, voc\00ea defende a mordida com sua espada e num movimento r\00e1pido, corta a cabe\00e7a do animal. Voc\00ea derrotou o Lobo Faminto!', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/564x/b7/bd/39/b7bd39d884231bcdba3dec0fb14d5fa8.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(24, U&'N\00e3o sabendo nada sobre o animal, por\00e9m confiante de que pode vencer, voc\00ea decide apenas deix\00e1-lo inconsciente. O lobo ataca, voc\00ea defende a mordida com sua espada e aproveita o movimento para jog\00e1-lo em dire\00e7\00e3o \00e0 parede com for\00e7a. O baque \00e9 forte, e ap\00f3s alguns segundos, voc\00ea percebe que ele n\00e3o est\00e1 mais se movimentando, ainda assim sua respira\00e7\00e3o est\00e1 est\00e1vel.', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/originals/b4/88/9e/b4889e49e0bfb3d4324da437be48398a.gif', 0, 0, 0, 0, 0, 0, 0, 0);             
INSERT INTO "PUBLIC"."TEXTOS" VALUES
(25, U&'Surpreso, por\00e9m n\00e3o acuado pelo ser lupino, voc\00ea decide partir para cima primeiro. O lobo n\00e3o recua, e faz um avan\00e7o r\00e1pido, tentando morder seu bra\00e7o. Voc\00ea consegue desviar por pouco, por\00e9m percebe que n\00e3o vai conseguir ganhar apenas na for\00e7a bruta.', 'Matar', 23, 'Nocautear', 24, '', 0, 'https://i.pinimg.com/originals/19/e2/07/19e207decb14968dbfc62a77664397ef.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(26, U&'Voc\00ea espera o ataque. O lobo faminto vem em sua dire\00e7\00e3o, mirando sua perna. Voc\00ea percebe as inten\00e7\00f5es dele e consegue se jogar para fora do ataque, se levantando logo em seguida e mantendo o preparo.', 'Contra-Ataque', 27, 'Mochila', 30, 'Fugir', 31, 'https://i.pinimg.com/originals/13/2f/f6/132ff6a328f668062cebf890634ae2fa.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(27, U&'Voc\00ea se prepara, e o lobo avan\00e7a novamente, buscando rasgar seu pesco\00e7o... Por\00e9m, j\00e1 sabendo seu curso de a\00e7\00e3o, voc\00ea consegue se esquivar e se posicionar em cima do lobo, usando seu peso para mant\00ea-lo no ch\00e3o.', 'Matar', 28, 'Nocautear', 29, '', 0, 'https://i.pinimg.com/originals/25/d8/51/25d851d4d2f31b922edfb6e3e03ac8f5.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(28, U&'Voc\00ea ent\00e3o usa toda sua for\00e7a em um golpe certeiro na cabe\00e7a do animal, diversas vezes. Ele at\00e9 tenta se defender e te arranhar, mas estava enfraquecido devido \00e0 fome, e voc\00ea consegue finaliz\00e1-lo.', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/originals/19/e2/07/19e207decb14968dbfc62a77664397ef.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(29, U&'Aproveitando da exaust\00e3o e fraqueza do animal, voc\00ea facilmente consegue nocaute\00e1-lo sem sofrer danos.', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/originals/9c/6c/57/9c6c57d4dade72ebd4e051eb0d92d44a.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(30, U&'Voc\00ea decide abrir sua mochila e tira um punhado de roupas e sua faca, enrolando as roupas em seu bra\00e7o pensando em amortecer um poss\00edvel dano. Voc\00ea equipou: Defesa improvisada e faca! O lobo ent\00e3o avan\00e7a novamente, buscando atacar seu pesco\00e7o! Voc\00ea ent\00e3o defende com seu bra\00e7o ''fortificado'', aguentando um bom dano. Aproveitando que o lobo estava mordendo suas roupas, voc\00ea esfaqueia o lobo com a m\00e3o livre, jorrando sangue na sala. Ele afrouxa a mordida, e voc\00ea o acerta novamente, logo voc\00ea percebe que ele n\00e3o \00e9 mais um problema.', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/originals/d1/72/02/d17202b45b42ba5fd7cce2f2ae298881.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(31, U&'Com um desespero imenso, voc\00ea tenta correr at\00e9 a pr\00f3xima porta... Escolha a porta:', 'PORTA1', 32, 'PORTA2', 33, '0', 0, 'https://i.pinimg.com/originals/bf/93/5e/bf935e9ec3a43a2795bfef4b9da1f21c.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(32, 'E consegue fugir.', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/originals/bf/93/5e/bf935e9ec3a43a2795bfef4b9da1f21c.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(33, U&'Por\00e9m o lobo morde sua perna no meio do caminho. Voc\00ea v\00ea a po\00e7a de sangue se formando antes dele arrancar sua cabe\00e7a...', 'Morte', 3, '', 0, '', 0, 'https://i.pinimg.com/originals/e2/77/dd/e277dd76ec07b3e7b55bd42fa75f1685.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(34, U&'Ao entrar no novo c\00f4modo, ele se assemelha a um o\00e1sis, tem diversas \00e1rvores com frutos chamativos e suculentos, um pequeno riacho cristalino, e uma sensa\00e7\00e3o de paz toma conta do seu corpo.', 'Descansar', 35, 'Sair', 37, 'Explorar', 39, 'https://i.pinimg.com/564x/d0/34/ee/d034ee97599394d1630ee4e552366327.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(35, U&'Cansado de suas aventuras anteriores, e com um ambiente t\00e3o convidativo, voc\00ea decide descansar um pouco. Voc\00ea se deita na costa de uma \00e1rvore, e tenta pegar no sono... Lentamente tudo se escurece...', 'Next', 36, '', 0, '', 0, 'https://i.pinimg.com/564x/26/d2/e9/26d2e952f492da627c742ae008f6f8df.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(36, U&'De repente, voc\00ea acorda num susto! Voc\00ea n\00e3o consegue mais sentir seu corpo direito, todas as paredes se tornaram pretas com inscri\00e7\00f5es vermelhas, voc\00ea n\00e3o consegue ler absolutamente nada, mas o c\00edrculo com s\00edmbolos em volta n\00e3o tem erro... \00c9 um ritual. Sem conseguir mexer seu corpo, uma faca \00e9 fincada em seu peito, sua respira\00e7\00e3o come\00e7a a fica descompassada, e voc\00ea sente o sangue saindo de seu corpo. ''Mais um sacrif\00edcio em nome do nosso Senhor!''', 'Morte', 3, '', 0, '', 0, 'https://i.pinimg.com/originals/ba/0d/5d/ba0d5da4688341cc0c0da14a9b5526c5.gif', 0, 0, 0, 0, 0, 0, 0, 0);            
INSERT INTO "PUBLIC"."TEXTOS" VALUES
(37, U&'Focado em seu objetivo, voc\00ea tenta sair da sala, mas n\00e3o acha nenhuma porta ou sa\00edda aparente como na sala anterior. Voc\00ea caminha por horas, por\00e9m sem muitos resultados.', 'Descansar', 35, 'Explorar', 38, '', 0, 'https://i.pinimg.com/originals/ba/0d/5d/ba0d5da4688341cc0c0da14a9b5526c5.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(38, U&'Voc\00ea decide explorar a sala, e com um pouco de esfor\00e7o consegue achar uma porta camuflada no meio de folhas e \00e1rvores, e decide sair da sala.', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/564x/35/27/92/35279239918e14099ee083e460525869.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(39, U&'Explorando mais a fundo o lugar, voc\00ea percebe algumas coisas... A sala \00e9 muito maior do que a outra que voc\00ea j\00e1 passou. O sol est\00e1 radiante, mesmo que o lugar seja fechado. Ent\00e3o logo voc\00ea tem a sensa\00e7\00e3o que tudo aquilo \00e9 apenas sua mente lhe pregando pe\00e7as...', 'Next', 40, '', 0, '', 0, 'https://i.pinimg.com/564x/c7/3d/cc/c73dcc62594e2d2bcdbc3f99597ff4f7.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(40, U&'Enquanto voc\00ea est\00e1 pensando, voc\00ea escuta algo se aproximando... Olhando melhor, \00e9 uma mulher. Seu rosto est\00e1 levemente sujo, seus olhos sem vida e \00e9 poss\00edvel notar diversas manchas de sangue nas roupas, m\00e3os e rosto dela. Ela nota que voc\00ea est\00e1 a observando e entra em choque. Voc\00ea nota o o\00e1sis se distorcendo um pouco.', 'Matar - Espada', 41, 'Matar - Faca', 42, 'Poupar', 43, 'https://i.pinimg.com/564x/e6/c7/9c/e6c79cbfaca53bcfc52c617dd4169bde.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(41, U&'Com sua espada em m\00e3os voc\00ea decide lutar contra a feiticeira, ela n\00e3o parece forte, por\00e9m voc\00ea n\00e3o sabe os truques que ela guarda. Enquanto ela corre, voc\00ea a persegue com facilidade e acerta um corte em sua perna, derrubando-a e saindo da ilus\00e3o, a porta est\00e1 logo \00e0 sua frente.', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/originals/0a/cc/ed/0accedf0f3d870e9f02ae83535cfa808.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(42, U&'Voc\00ea pega a faca que estava em sua mochila e atira na ilusionista, derrubando-a no ch\00e3o. Com um corte limpo, voc\00ea mata a feiticeira.', 'Sucesso', 44, '', 0, '', 0, 'https://i.pinimg.com/originals/af/fe/75/affe75397246a1730db91980e7fb108d.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(43, U&'Vendo o rosto aterrorizado da mulher, voc\00ea decide n\00e3o matar ela, e sai em dire\00e7\00e3o \00e0 pr\00f3xima sala.', 'Sucesso', 44, '', 0, '', 0, 'https://c8.alamy.com/comp/2C2A99C/vector-pixel-art-woman-ghost-isolated-cartoon-2C2A99C.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(44, U&'Ao entrar no novo c\00f4modo, o ambiente est\00e1 mais sereno, voc\00ea n\00e3o v\00ea inimigos, no centro \00e9 poss\00edvel ver algo como uma tela de computador com uma mensagem:', 'TELA1', 45, 'TELA2', 46, 'TELA3', 47, 'https://i.pinimg.com/564x/6a/f0/31/6af0317c9e537d677906043c1bcf798f.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(45, U&'Eu posso ser o Sol, eu posso ser areia, eu posso ser um p\00e1ssaro, o que eu sou?', 'Relogio', 48, 'Fenix', 49, 'Praia', 49, '', 0, 0, 0, 0, 0, 0, 0, 0),
(46, 'Eu posso ser um Deus, um planeta, e medir o calor. O que eu sou?', 'Jupiter', 49, 'Apolo', 49, 'Mercurio', 48, 'https://img.freepik.com/vetores-premium/colecao-pixel-of-the-planet-de-8-bits-para-ativos-de-jogos-em-ilustracoes-vetoriais_614713-758.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(47, U&'Eu tenho lagos sem \00e1gua, montanhas sem pedra e cidades sem pr\00e9dios. O que eu sou?', U&'Imagina\00e7\00e3o', 49, 'Mapa', 51, U&'Proje\00e7\00e3o', 49, 'https://i.pinimg.com/originals/5a/90/94/5a9094b188f6b8398e9649af28255654.png', 0, 0, 0, 0, 0, 0, 0, 0),
(48, 'O estranho mecanismo recebe sua resposta e analisa por alguns segundos...', 'ACERTO', 51, 'ERRO', 49, '', 0, 'https://64.media.tumblr.com/32f47e684ded07673d241b4ccc3f14e2/tumblr_o0w5xvQpa91v50ozko1_640.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(49, '[Resposta INCORRETA]', 'NEXT', 50, '', 0, '', 0, 'https://i.pinimg.com/564x/db/1e/1b/db1e1bdbf7cb5e08888f78ebace9bf65.jpg', 0, 0, 0, 0, 0, 0, 0, 0);     
INSERT INTO "PUBLIC"."TEXTOS" VALUES
(50, U&'Ent\00e3o de todas as paredes e do teto, voc\00ea pode ver l\00e2minas se formando magicamente como espinhos. Voc\00ea n\00e3o tem como desviar. Sem tempo para reagir, as l\00e2minas s\00e3o lan\00e7adas a uma velocidade absurda em voc\00ea.', '', 0, '', 0, '', 0, 'https://i.pinimg.com/564x/fa/b6/50/fab650086cec4002671f8e9a9a2288d7.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(51, U&'[Resposta CORRETA] A tela pisca em verde e voc\00ea pode ver uma das paredes descendo lentamente, revelando uma nova passagem.', 'NEXT', 52, '', 0, '', 0, 'https://as2.ftcdn.net/v2/jpg/05/33/03/01/1000_F_533030174_JQXl9PwbHvFTxiWJNe2ZMBrHDBFPRAl6.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(52, U&'Voc\00ea passou da sala do enigma!', 'NEXT', 55, '', 0, '', 0, 'https://cdn3.vectorstock.com/i/1000x1000/11/42/congratulations-in-speech-bubble-8-bit-pixel-art-vector-24721142.jpg', 0, 0, 0, 0, 0, 0, 0, 0),
(55, U&'O corredor para o pr\00f3ximo c\00f4modo te d\00e1 calafrios, um tom acinzentado est\00e1 sempre presente nessa curta jornada, e conforme voc\00ea se aproxima da pr\00f3xima porta, tons de vermelho sangue tomam o lugar em todas as paredes... Voc\00ea abre a pr\00f3xima porta e encontra uma sala enorme, com diversos cr\00e2nios espalhados pelo ch\00e3o, uma ponte de cabe\00e7as levando ao centro, onde se pode ver um trono, e alguma coisa est\00e1 sentada, esperando...\\n', 'Next', 56, '0', 0, '0', 0, 'https://i.pinimg.com/originals/79/4d/83/794d83a1cc114ae3097dcfc924e9ddc4.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(56, U&'Olha s\00f3, o humano tem algum potencial... Diga-me, o que busca nesse dom\00ednio?''\\n Uma criatura completamente vermelha, com asas escuras saindo de suas costas e um par de chifres, questiona sua determina\00e7\00e3o, independente do que isso seja, voc\00ea sabe que qualquer decis\00e3o n\00e3o ser\00e1 simples aqui... O que quer fazer?', 'Lutar', 57, 'Fugir', 58, '0', 0, 'https://i.pinimg.com/originals/1c/3a/9b/1c3a9bc1c91135ff036d1d168d15e474.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(57, U&'N\00e3o \00e9 muito de falar, n\00e3o \00e9 mesmo? Mas suas inten\00e7\00f5es est\00e3o claras. A criatura se levanta e se posiciona na sua frente com um olhar hostil', 'NEXT', 59, '0', 0, '0', 0, 'https://i.pinimg.com/originals/1c/3a/9b/1c3a9bc1c91135ff036d1d168d15e474.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(58, U&'Temendo a criatura, voc\00ea tenta sair pela porta onde voltou, o dem\00f4nio abre ela com magia e voc\00ea corre, como se n\00e3o houvesse amanh\00e3...\\n Uma, duas, tr\00eas portas, e ent\00e3o a \00faltima porta finalmente se abre... Voc\00ea volta \00e0 sala do dem\00f4nio, que n\00e3o parece muito feliz por voc\00ea ter tentado fugir... Ele voa rapidamente, e em um instante, sua cabe\00e7a est\00e1 no ch\00e3o...\\n', 'Next', 3, '0', 0, '0', 0, 'https://i.pinimg.com/originals/bf/93/5e/bf935e9ec3a43a2795bfef4b9da1f21c.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(59, U&'Voc\00ea inicia uma batalha contra ele, se prepare', 'Next', 60, '0', 0, '0', 0, 'https://i.pinimg.com/originals/d8/7a/07/d87a07cfb80d11cb4e768291699f069c.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(60, 'O que deseja fazer ? ', 'Atacar', 61, 'Defender', 66, 'Esquivar', 67, 'https://i.pinimg.com/originals/d8/7a/07/d87a07cfb80d11cb4e768291699f069c.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(61, U&'Voc\00ea acerta! O demonio perde vida!', 'Next', 60, '0', 0, '0', 0, 'https://i.pinimg.com/originals/0a/cc/ed/0accedf0f3d870e9f02ae83535cfa808.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(62, 'Voce errou, aguarde a proxma chance. Vez do Demonio, prepare-se.', 'Next', 63, '0', 0, '0', 0, 'https://i.pinimg.com/originals/7c/52/d5/7c52d590b52375b1b52a00a294695a18.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(63, U&'Voc\00ea errou o seu ataque!       Vez do Demonio: O Demonio Acertou', 'Next', 60, '0', 0, '0', 0, 'https://i.pinimg.com/originals/1c/3a/9b/1c3a9bc1c91135ff036d1d168d15e474.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(64, U&'Voc\00ea errou o seu ataque! Vez do Demonio: O demonio errou', 'Next', 60, '0', 0, '0', 0, 'https://i.pinimg.com/originals/c7/6c/87/c76c873ca7d63b7fb29792ad26d36368.gif', 0, 0, 0, 0, 0, 0, 0, 0),
(66, 'Voce se posiciona para uma defesa ao ataque do inimigo! Sucesso.', 'Next', 60, '0', 0, '0', 0, 'https://i.pinimg.com/564x/83/43/9a/83439a78de0a12c63db6fd2221664b6c.jpg', 0, 0, 0, 0, 0, 0, 0, 0);         
INSERT INTO "PUBLIC"."TEXTOS" VALUES
(67, 'Voce resolve esperar o ataque do oponente e realizar uma esquiva!', 'Next', 60, '0', 0, '0', 0, 'https://cdna.artstation.com/p/assets/images/images/023/869/474/original/kyle-mcarthur-moon-dodge-right-new.gif?1580604790', 0, 0, 0, 0, 0, 0, 0, 0);             
